=== tr1cks/weather-service/core/src/main/resources/openweathermap/current-weather.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns="current-weather" targetNamespace="current-weather"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="current" type="currentWeather"/>

    <xs:complexType name="currentWeather">
        <xs:sequence>
            <xs:element name="city" type="city"/>
            <xs:element name="temperature" type="temperature"/>
            <xs:element name="humidity" type="humidity"/>
            <xs:element name="pressure" type="pressure"/>
            <xs:element name="wind" type="wind"/>
            <xs:element name="clouds" type="clouds"/>
            <xs:element name="visibility" type="xs:string"/>
            <xs:element name="precipitation" type="precipitation"/>
            <xs:element name="weather" type="weather"/>
            <xs:element name="lastupdate" type="lastUpdate"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="city">
        <xs:sequence>
            <xs:element name="coord" type="coord" />
            <xs:element name="country" type="xs:string" />
            <xs:element name="sun" type="sun" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" />
        <xs:attribute name="name" type="xs:string" />
    </xs:complexType>
    <xs:complexType name="coord">
        <xs:attribute name="lon" type="xs:double" />
        <xs:attribute name="lat" type="xs:double"/>
    </xs:complexType>
    <xs:complexType name="sun">
        <xs:attribute name="rise" type="xs:dateTime" />
        <xs:attribute name="set" type="xs:dateTime"/>
    </xs:complexType>

    <xs:complexType name="temperature">
        <xs:attribute name="value" type="xs:double"/>
        <xs:attribute name="min" type="xs:double"/>
        <xs:attribute name="max" type="xs:double"/>
        <xs:attribute name="unit" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="humidity">
        <xs:attribute name="value" type="xs:byte"/>
        <xs:attribute name="unit" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="pressure">
        <xs:attribute name="value" type="xs:double"/>
        <xs:attribute name="unit" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="wind">
        <xs:sequence>
            <xs:element name="speed" type="speed"/>
            <xs:element name="direction" type="direction"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="speed">
        <xs:attribute name="value" type="xs:double"/>
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="direction">
        <xs:attribute name="value" type="xs:double"/>
        <xs:attribute name="code" type="xs:string"/>
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="clouds">
        <xs:attribute name="value" type="xs:byte"/>
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="precipitation">
        <xs:attribute name="value" type="xs:double"/>
        <xs:attribute name="mode" type="xs:string" use="required"/>
        <xs:attribute name="unit" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="weather">
        <xs:attribute name="number" type="xs:short"/>
        <xs:attribute name="value" type="xs:string"/>
        <xs:attribute name="icon" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="lastUpdate">
        <xs:attribute name="value" type="xs:dateTime"/>
    </xs:complexType>
</xs:schema>

=== tr1cks/weather-service/core/src/test/resources/openweathermap/current-London.xml
<?xml version="1.0" encoding="utf-8"?>
<current xmlns="current-weather"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="current-weather current-weather.xsd">
    <city id="2643743" name="London">
        <coord lon="-0.13" lat="51.51"/>
        <country>GB</country>
        <sun rise="2014-08-10T04:38:59" set="2014-08-10T19:32:38"/>
    </city>
    <temperature value="20.21" min="18" max="22.22" unit="celsius"/>
    <humidity value="83" unit="%"/>
    <pressure value="992" unit="hPa"/>
    <wind>
        <speed value="7.7" name="Moderate breeze"/>
        <direction value="200" code="SSW" name="South-southwest"/>
    </wind>
    <clouds value="75" name="broken clouds"/>
    <visibility/>
    <precipitation value="0.75" mode="rain" unit="3h"/>
    <weather number="521" value="дождь" icon="09d"/>
    <lastupdate value="2014-08-10T12:09:17"/>
</current>

=== tr1cks/weather-service/core/src/test/resources/openweathermap/current-Moscow.xml
<?xml version="1.0" encoding="utf-8"?>
<current xmlns="current-weather"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="current-weather current-weather.xsd">
    <city id="524901" name="Moscow">
        <coord lon="37.62" lat="55.75"/>
        <country>RU</country>
        <sun rise="2014-08-10T01:52:38" set="2014-08-10T17:17:01"/>
    </city>
    <temperature value="28.33" min="25.56" max="30.6" unit="celsius"/>
    <humidity value="47" unit="%"/>
    <pressure value="1011" unit="hPa"/>
    <wind>
        <speed value="4" name="Gentle Breeze"/>
        <direction value="310" code="NW" name="Northwest"/>
    </wind>
    <clouds value="0" name="clear sky"/>
    <visibility/>
    <precipitation mode="no"/>
    <weather number="800" value="ясно" icon="01d"/>
    <lastupdate value="2014-08-10T11:53:39"/>
</current>

=== tr1cks/weather-service/core/src/test/resources/openweathermap/current-Yekaterinburg.xml
<?xml version="1.0" encoding="utf-8"?>
<current xmlns="current-weather"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="current-weather current-weather.xsd">
    <city id="1486209" name="Yekaterinburg">
        <coord lon="60.61" lat="56.86"/>
        <country>RU</country>
        <sun rise="2014-08-10T00:15:55" set="2014-08-10T15:49:50"/>
    </city>
    <temperature value="30" min="30" max="30" unit="celsius"/>
    <humidity value="42" unit="%"/>
    <pressure value="1007" unit="hPa"/>
    <wind>
        <speed value="5" name="Gentle Breeze"/>
        <direction value="170" code="S" name="South"/>
    </wind>
    <clouds value="0" name="clear sky"/>
    <visibility/>
    <precipitation mode="no"/>
    <weather number="800" value="ясно" icon="01d"/>
    <lastupdate value="2014-08-10T11:09:09"/>
</current>
